### ISSUE TITLE
Depth loss change

### ISSUE THREAD

**Issue by haowang020110** [lastbasket/Endo-4DGS#4]
Dear author
Thanks to your work at first!
In your paper, you mentioned a pearson loss for depth regularization.
But in the train code I found only l1 loss was used. I am wondering the reason for this change.

**Comment by lastbasket** [comment]
Sorry for the inconvenience, the implementation is hided in https://github.com/lastbasket/Endo-4DGS/blob/6d08b85f31fedaf0d7da0ef1c28e85519fecdae0/utils/loss_utils.py#L377
